apiVersion: v1
kind: Service
metadata:
  name: {{ include "sifnode.fullname" . }}
  labels:
    {{- include "sifnode.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Local
  type: {{ .Values.sifnode.service.type }}
  ports:
    - port: 26656
      targetPort: 26656
      protocol: TCP
      name: port-26656
    - port: 26657
      targetPort: 26657
      protocol: TCP
      name: port-26657
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: port-6060
  selector:
    {{- include "sifnode.selectorLabels" . | nindent 4 }}
